//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 12:37:13 PM EEST 
//


package siima.models.jaxb.caex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * CAEX basis object derived from CAEXBasicObject, augmented by 
 * Name (required) and ID (optional).
 * 
 * <p>Java class for CAEXObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CAEXObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}CAEXBasicObject"&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAEXObject")
@XmlSeeAlso({
    siima.models.jaxb.caex.CAEXFile.InstanceHierarchy.class,
    siima.models.jaxb.caex.CAEXFile.InterfaceClassLib.class,
    siima.models.jaxb.caex.CAEXFile.RoleClassLib.class,
    siima.models.jaxb.caex.CAEXFile.SystemUnitClassLib.class,
    InterfaceClassType.class,
    RoleClassType.class,
    SystemUnitClassType.InternalLink.class,
    SystemUnitClassType.class,
    AttributeType.class
})
public class CAEXObject
    extends CAEXBasicObject
{

    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
