//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 12:37:13 PM EEST 
//


package siima.models.jaxb.caex;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the siima.models.jaxb.caex package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * ---------------------------
 * VPA: ADDITIONS:(2017-06-2)
 * ADD: AppInfoEXTRAContentType.java 
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: siima.models.jaxb.caex
     * 
     */
    public ObjectFactory() {
    }

	 /**
     * Create an instance of {@link AppInfoEXTRAContentType }
     * (2017-06-2) VPA: Extra class)
     */
    public AppInfoEXTRAContentType createAppInfoEXTRAContentType() {
        return new AppInfoEXTRAContentType();
    }

    /**
     * Create an instance of {@link AppInfoEXTRAContentType.WriterHeader }
     * (2017-06-2) VPA: Extra class)
     */
    public AppInfoEXTRAContentType.WriterHeader createAppInfoEXTRAContentTypeWriterHeader() {
        return new AppInfoEXTRAContentType.WriterHeader();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AppInfoEXTRAContentType }{@code >}}
     * (2017-06-2) VPA: Extra class)
    
    @XmlElementDecl(namespace = "", name = "AppInfoEXTRAContent")
    public JAXBElement<AppInfoEXTRAContentType> createAppInfoEXTRAContent(AppInfoEXTRAContentType value) {
        return new JAXBElement<AppInfoEXTRAContentType>(_AppInfoEXTRAContent_QNAME, AppInfoEXTRAContentType.class, null, value);
    }
	 */
    
	
    /**
     * Create an instance of {@link CAEXBasicObject }
     * 
     */
    public CAEXBasicObject createCAEXBasicObject() {
        return new CAEXBasicObject();
    }

    /**
     * Create an instance of {@link CAEXFile }
     * 
     */
    public CAEXFile createCAEXFile() {
        return new CAEXFile();
    }

    /**
     * Create an instance of {@link MappingType }
     * 
     */
    public MappingType createMappingType() {
        return new MappingType();
    }

    /**
     * Create an instance of {@link AttributeValueRequirementType }
     * 
     */
    public AttributeValueRequirementType createAttributeValueRequirementType() {
        return new AttributeValueRequirementType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link SystemUnitClassType }
     * 
     */
    public SystemUnitClassType createSystemUnitClassType() {
        return new SystemUnitClassType();
    }

    /**
     * Create an instance of {@link InternalElementType }
     * 
     */
    public InternalElementType createInternalElementType() {
        return new InternalElementType();
    }

    /**
     * Create an instance of {@link RoleClassType }
     * 
     */
    public RoleClassType createRoleClassType() {
        return new RoleClassType();
    }

    /**
     * Create an instance of {@link CAEXBasicObject.Description }
     * 
     */
    public CAEXBasicObject.Description createCAEXBasicObjectDescription() {
        return new CAEXBasicObject.Description();
    }

    /**
     * Create an instance of {@link CAEXBasicObject.Version }
     * 
     */
    public CAEXBasicObject.Version createCAEXBasicObjectVersion() {
        return new CAEXBasicObject.Version();
    }

    /**
     * Create an instance of {@link CAEXBasicObject.Revision }
     * 
     */
    public CAEXBasicObject.Revision createCAEXBasicObjectRevision() {
        return new CAEXBasicObject.Revision();
    }

    /**
     * Create an instance of {@link CAEXBasicObject.Copyright }
     * 
     */
    public CAEXBasicObject.Copyright createCAEXBasicObjectCopyright() {
        return new CAEXBasicObject.Copyright();
    }

    /**
     * Create an instance of {@link CAEXFile.ExternalReference }
     * 
     */
    public CAEXFile.ExternalReference createCAEXFileExternalReference() {
        return new CAEXFile.ExternalReference();
    }

    /**
     * Create an instance of {@link CAEXFile.InstanceHierarchy }
     * 
     */
    public CAEXFile.InstanceHierarchy createCAEXFileInstanceHierarchy() {
        return new CAEXFile.InstanceHierarchy();
    }

    /**
     * Create an instance of {@link CAEXFile.InterfaceClassLib }
     * 
     */
    public CAEXFile.InterfaceClassLib createCAEXFileInterfaceClassLib() {
        return new CAEXFile.InterfaceClassLib();
    }

    /**
     * Create an instance of {@link CAEXFile.RoleClassLib }
     * 
     */
    public CAEXFile.RoleClassLib createCAEXFileRoleClassLib() {
        return new CAEXFile.RoleClassLib();
    }

    /**
     * Create an instance of {@link CAEXFile.SystemUnitClassLib }
     * 
     */
    public CAEXFile.SystemUnitClassLib createCAEXFileSystemUnitClassLib() {
        return new CAEXFile.SystemUnitClassLib();
    }

    /**
     * Create an instance of {@link CAEXObject }
     * 
     */
    public CAEXObject createCAEXObject() {
        return new CAEXObject();
    }

    /**
     * Create an instance of {@link InterfaceClassType }
     * 
     */
    public InterfaceClassType createInterfaceClassType() {
        return new InterfaceClassType();
    }

    /**
     * Create an instance of {@link InterfaceFamilyType }
     * 
     */
    public InterfaceFamilyType createInterfaceFamilyType() {
        return new InterfaceFamilyType();
    }

    /**
     * Create an instance of {@link RoleFamilyType }
     * 
     */
    public RoleFamilyType createRoleFamilyType() {
        return new RoleFamilyType();
    }

    /**
     * Create an instance of {@link SystemUnitFamilyType }
     * 
     */
    public SystemUnitFamilyType createSystemUnitFamilyType() {
        return new SystemUnitFamilyType();
    }

    /**
     * Create an instance of {@link MappingType.AttributeNameMapping }
     * 
     */
    public MappingType.AttributeNameMapping createMappingTypeAttributeNameMapping() {
        return new MappingType.AttributeNameMapping();
    }

    /**
     * Create an instance of {@link MappingType.InterfaceNameMapping }
     * 
     */
    public MappingType.InterfaceNameMapping createMappingTypeInterfaceNameMapping() {
        return new MappingType.InterfaceNameMapping();
    }

    /**
     * Create an instance of {@link AttributeValueRequirementType.OrdinalScaledType }
     * 
     */
    public AttributeValueRequirementType.OrdinalScaledType createAttributeValueRequirementTypeOrdinalScaledType() {
        return new AttributeValueRequirementType.OrdinalScaledType();
    }

    /**
     * Create an instance of {@link AttributeValueRequirementType.NominalScaledType }
     * 
     */
    public AttributeValueRequirementType.NominalScaledType createAttributeValueRequirementTypeNominalScaledType() {
        return new AttributeValueRequirementType.NominalScaledType();
    }

    /**
     * Create an instance of {@link AttributeValueRequirementType.UnknownType }
     * 
     */
    public AttributeValueRequirementType.UnknownType createAttributeValueRequirementTypeUnknownType() {
        return new AttributeValueRequirementType.UnknownType();
    }

    /**
     * Create an instance of {@link AttributeType.RefSemantic }
     * 
     */
    public AttributeType.RefSemantic createAttributeTypeRefSemantic() {
        return new AttributeType.RefSemantic();
    }

    /**
     * Create an instance of {@link SystemUnitClassType.SupportedRoleClass }
     * 
     */
    public SystemUnitClassType.SupportedRoleClass createSystemUnitClassTypeSupportedRoleClass() {
        return new SystemUnitClassType.SupportedRoleClass();
    }

    /**
     * Create an instance of {@link SystemUnitClassType.InternalLink }
     * 
     */
    public SystemUnitClassType.InternalLink createSystemUnitClassTypeInternalLink() {
        return new SystemUnitClassType.InternalLink();
    }

    /**
     * Create an instance of {@link InternalElementType.RoleRequirements }
     * 
     */
    public InternalElementType.RoleRequirements createInternalElementTypeRoleRequirements() {
        return new InternalElementType.RoleRequirements();
    }

    /**
     * Create an instance of {@link RoleClassType.ExternalInterface }
     * 
     */
    public RoleClassType.ExternalInterface createRoleClassTypeExternalInterface() {
        return new RoleClassType.ExternalInterface();
    }

}
