//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.03 at 01:27:51 PM EEST 
//


package siima.models.jaxb.caex3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SourceDocumentInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceDocumentInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="OriginName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginVendor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginVendorURL" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginRelease" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="LastWritingDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" /&gt;
 *       &lt;attribute name="OriginProjectTitle" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="OriginProjectID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceDocumentInformationType")
public class SourceDocumentInformationType {

    @XmlAttribute(name = "OriginName", required = true)
    protected String originName;
    @XmlAttribute(name = "OriginID", required = true)
    protected String originID;
    @XmlAttribute(name = "OriginVendor")
    protected String originVendor;
    @XmlAttribute(name = "OriginVendorURL")
    protected String originVendorURL;
    @XmlAttribute(name = "OriginVersion", required = true)
    protected String originVersion;
    @XmlAttribute(name = "OriginRelease")
    protected String originRelease;
    @XmlAttribute(name = "LastWritingDateTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastWritingDateTime;
    @XmlAttribute(name = "OriginProjectTitle")
    protected String originProjectTitle;
    @XmlAttribute(name = "OriginProjectID")
    protected String originProjectID;

    /**
     * Gets the value of the originName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * Sets the value of the originName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginName(String value) {
        this.originName = value;
    }

    /**
     * Gets the value of the originID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginID() {
        return originID;
    }

    /**
     * Sets the value of the originID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginID(String value) {
        this.originID = value;
    }

    /**
     * Gets the value of the originVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginVendor() {
        return originVendor;
    }

    /**
     * Sets the value of the originVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginVendor(String value) {
        this.originVendor = value;
    }

    /**
     * Gets the value of the originVendorURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginVendorURL() {
        return originVendorURL;
    }

    /**
     * Sets the value of the originVendorURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginVendorURL(String value) {
        this.originVendorURL = value;
    }

    /**
     * Gets the value of the originVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginVersion() {
        return originVersion;
    }

    /**
     * Sets the value of the originVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginVersion(String value) {
        this.originVersion = value;
    }

    /**
     * Gets the value of the originRelease property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginRelease() {
        return originRelease;
    }

    /**
     * Sets the value of the originRelease property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginRelease(String value) {
        this.originRelease = value;
    }

    /**
     * Gets the value of the lastWritingDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastWritingDateTime() {
        return lastWritingDateTime;
    }

    /**
     * Sets the value of the lastWritingDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastWritingDateTime(XMLGregorianCalendar value) {
        this.lastWritingDateTime = value;
    }

    /**
     * Gets the value of the originProjectTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginProjectTitle() {
        return originProjectTitle;
    }

    /**
     * Sets the value of the originProjectTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginProjectTitle(String value) {
        this.originProjectTitle = value;
    }

    /**
     * Gets the value of the originProjectID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginProjectID() {
        return originProjectID;
    }

    /**
     * Sets the value of the originProjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginProjectID(String value) {
        this.originProjectID = value;
    }

}
