//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.10 at 04:40:43 ip. EEST 
//


package siima.models.jaxb.caex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}CAEXBasicObject">
 *       &lt;sequence>
 *         &lt;element name="ExternalReference" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXBasicObject">
 *                 &lt;attribute name="Path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InstanceHierarchy" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXObject">
 *                 &lt;sequence>
 *                   &lt;element name="InternalElement" type="{}InternalElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InterfaceClassLib" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXObject">
 *                 &lt;sequence>
 *                   &lt;element name="InterfaceClass" type="{}InterfaceFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoleClassLib" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXObject">
 *                 &lt;sequence>
 *                   &lt;element name="RoleClass" type="{}RoleFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SystemUnitClassLib" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXObject">
 *                 &lt;sequence>
 *                   &lt;element name="SystemUnitClass" type="{}SystemUnitFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="FileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="2.15" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "externalReference",
    "instanceHierarchy",
    "interfaceClassLib",
    "roleClassLib",
    "systemUnitClassLib"
})
@XmlRootElement(name = "CAEXFile")
public class CAEXFile
    extends CAEXBasicObject
{

    @XmlElement(name = "ExternalReference")
    protected List<CAEXFile.ExternalReference> externalReference;
    @XmlElement(name = "InstanceHierarchy")
    protected List<CAEXFile.InstanceHierarchy> instanceHierarchy;
    @XmlElement(name = "InterfaceClassLib")
    protected List<CAEXFile.InterfaceClassLib> interfaceClassLib;
    @XmlElement(name = "RoleClassLib")
    protected List<CAEXFile.RoleClassLib> roleClassLib;
    @XmlElement(name = "SystemUnitClassLib")
    protected List<CAEXFile.SystemUnitClassLib> systemUnitClassLib;
    @XmlAttribute(name = "FileName", required = true)
    protected String fileName;
    @XmlAttribute(name = "SchemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the externalReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CAEXFile.ExternalReference }
     * 
     * 
     */
    public List<CAEXFile.ExternalReference> getExternalReference() {
        if (externalReference == null) {
            externalReference = new ArrayList<CAEXFile.ExternalReference>();
        }
        return this.externalReference;
    }

    public boolean isSetExternalReference() {
        return ((this.externalReference!= null)&&(!this.externalReference.isEmpty()));
    }

    public void unsetExternalReference() {
        this.externalReference = null;
    }

    /**
     * Gets the value of the instanceHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CAEXFile.InstanceHierarchy }
     * 
     * 
     */
    public List<CAEXFile.InstanceHierarchy> getInstanceHierarchy() {
        if (instanceHierarchy == null) {
            instanceHierarchy = new ArrayList<CAEXFile.InstanceHierarchy>();
        }
        return this.instanceHierarchy;
    }

    public boolean isSetInstanceHierarchy() {
        return ((this.instanceHierarchy!= null)&&(!this.instanceHierarchy.isEmpty()));
    }

    public void unsetInstanceHierarchy() {
        this.instanceHierarchy = null;
    }

    /**
     * Gets the value of the interfaceClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CAEXFile.InterfaceClassLib }
     * 
     * 
     */
    public List<CAEXFile.InterfaceClassLib> getInterfaceClassLib() {
        if (interfaceClassLib == null) {
            interfaceClassLib = new ArrayList<CAEXFile.InterfaceClassLib>();
        }
        return this.interfaceClassLib;
    }

    public boolean isSetInterfaceClassLib() {
        return ((this.interfaceClassLib!= null)&&(!this.interfaceClassLib.isEmpty()));
    }

    public void unsetInterfaceClassLib() {
        this.interfaceClassLib = null;
    }

    /**
     * Gets the value of the roleClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CAEXFile.RoleClassLib }
     * 
     * 
     */
    public List<CAEXFile.RoleClassLib> getRoleClassLib() {
        if (roleClassLib == null) {
            roleClassLib = new ArrayList<CAEXFile.RoleClassLib>();
        }
        return this.roleClassLib;
    }

    public boolean isSetRoleClassLib() {
        return ((this.roleClassLib!= null)&&(!this.roleClassLib.isEmpty()));
    }

    public void unsetRoleClassLib() {
        this.roleClassLib = null;
    }

    /**
     * Gets the value of the systemUnitClassLib property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemUnitClassLib property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemUnitClassLib().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CAEXFile.SystemUnitClassLib }
     * 
     * 
     */
    public List<CAEXFile.SystemUnitClassLib> getSystemUnitClassLib() {
        if (systemUnitClassLib == null) {
            systemUnitClassLib = new ArrayList<CAEXFile.SystemUnitClassLib>();
        }
        return this.systemUnitClassLib;
    }

    public boolean isSetSystemUnitClassLib() {
        return ((this.systemUnitClassLib!= null)&&(!this.systemUnitClassLib.isEmpty()));
    }

    public void unsetSystemUnitClassLib() {
        this.systemUnitClassLib = null;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    public boolean isSetFileName() {
        return (this.fileName!= null);
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "2.15";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    public boolean isSetSchemaVersion() {
        return (this.schemaVersion!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXBasicObject">
     *       &lt;attribute name="Path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Alias" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ExternalReference
        extends CAEXBasicObject
    {

        @XmlAttribute(name = "Path", required = true)
        protected String path;
        @XmlAttribute(name = "Alias", required = true)
        protected String alias;

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

        public boolean isSetPath() {
            return (this.path!= null);
        }

        /**
         * Gets the value of the alias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlias() {
            return alias;
        }

        /**
         * Sets the value of the alias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlias(String value) {
            this.alias = value;
        }

        public boolean isSetAlias() {
            return (this.alias!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="InternalElement" type="{}InternalElementType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "internalElement"
    })
    public static class InstanceHierarchy
        extends CAEXObject
    {

        @XmlElement(name = "InternalElement")
        protected List<InternalElementType> internalElement;

        /**
         * Gets the value of the internalElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the internalElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInternalElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InternalElementType }
         * 
         * 
         */
        public List<InternalElementType> getInternalElement() {
            if (internalElement == null) {
                internalElement = new ArrayList<InternalElementType>();
            }
            return this.internalElement;
        }

        public boolean isSetInternalElement() {
            return ((this.internalElement!= null)&&(!this.internalElement.isEmpty()));
        }

        public void unsetInternalElement() {
            this.internalElement = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="InterfaceClass" type="{}InterfaceFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interfaceClass"
    })
    public static class InterfaceClassLib
        extends CAEXObject
    {

        @XmlElement(name = "InterfaceClass")
        protected List<InterfaceFamilyType> interfaceClass;

        /**
         * Gets the value of the interfaceClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interfaceClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInterfaceClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InterfaceFamilyType }
         * 
         * 
         */
        public List<InterfaceFamilyType> getInterfaceClass() {
            if (interfaceClass == null) {
                interfaceClass = new ArrayList<InterfaceFamilyType>();
            }
            return this.interfaceClass;
        }

        public boolean isSetInterfaceClass() {
            return ((this.interfaceClass!= null)&&(!this.interfaceClass.isEmpty()));
        }

        public void unsetInterfaceClass() {
            this.interfaceClass = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="RoleClass" type="{}RoleFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "roleClass"
    })
    public static class RoleClassLib
        extends CAEXObject
    {

        @XmlElement(name = "RoleClass")
        protected List<RoleFamilyType> roleClass;

        /**
         * Gets the value of the roleClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the roleClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRoleClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RoleFamilyType }
         * 
         * 
         */
        public List<RoleFamilyType> getRoleClass() {
            if (roleClass == null) {
                roleClass = new ArrayList<RoleFamilyType>();
            }
            return this.roleClass;
        }

        public boolean isSetRoleClass() {
            return ((this.roleClass!= null)&&(!this.roleClass.isEmpty()));
        }

        public void unsetRoleClass() {
            this.roleClass = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;sequence>
     *         &lt;element name="SystemUnitClass" type="{}SystemUnitFamilyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemUnitClass"
    })
    public static class SystemUnitClassLib
        extends CAEXObject
    {

        @XmlElement(name = "SystemUnitClass")
        protected List<SystemUnitFamilyType> systemUnitClass;

        /**
         * Gets the value of the systemUnitClass property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemUnitClass property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystemUnitClass().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SystemUnitFamilyType }
         * 
         * 
         */
        public List<SystemUnitFamilyType> getSystemUnitClass() {
            if (systemUnitClass == null) {
                systemUnitClass = new ArrayList<SystemUnitFamilyType>();
            }
            return this.systemUnitClass;
        }

        public boolean isSetSystemUnitClass() {
            return ((this.systemUnitClass!= null)&&(!this.systemUnitClass.isEmpty()));
        }

        public void unsetSystemUnitClass() {
            this.systemUnitClass = null;
        }

    }

}
