//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.10 at 04:40:43 ip. EEST 
//


package siima.models.jaxb.caex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * CAEX basis object derived from CAEXBasicObject, augmented by 
 * Name (required) and ID (optional).
 * 
 * <p>Java class for CAEXObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CAEXObject">
 *   &lt;complexContent>
 *     &lt;extension base="{}CAEXBasicObject">
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAEXObject")
@XmlSeeAlso({
    siima.models.jaxb.caex.CAEXFile.InstanceHierarchy.class,
    siima.models.jaxb.caex.CAEXFile.InterfaceClassLib.class,
    siima.models.jaxb.caex.CAEXFile.RoleClassLib.class,
    siima.models.jaxb.caex.CAEXFile.SystemUnitClassLib.class,
    AttributeType.class,
    InterfaceClassType.class,
    RoleClassType.class,
    SystemUnitClassType.InternalLink.class,
    SystemUnitClassType.class
})
public class CAEXObject
    extends CAEXBasicObject
{

    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    public boolean isSetID() {
        return (this.id!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
