//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.10 at 04:40:43 ip. EEST 
//


package siima.models.jaxb.caex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines base structures for a hierarchical RoleClass tree. The hierarchical structure of a role library has organizational character only. 
 * 
 * <p>Java class for RoleFamilyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoleFamilyType">
 *   &lt;complexContent>
 *     &lt;extension base="{}RoleClassType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="RoleClass" type="{}RoleFamilyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleFamilyType", propOrder = {
    "roleClass"
})
public class RoleFamilyType
    extends RoleClassType
{

    @XmlElement(name = "RoleClass")
    protected List<RoleFamilyType> roleClass;

    /**
     * Gets the value of the roleClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roleClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoleClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleFamilyType }
     * 
     * 
     */
    public List<RoleFamilyType> getRoleClass() {
        if (roleClass == null) {
            roleClass = new ArrayList<RoleFamilyType>();
        }
        return this.roleClass;
    }

    public boolean isSetRoleClass() {
        return ((this.roleClass!= null)&&(!this.roleClass.isEmpty()));
    }

    public void unsetRoleClass() {
        this.roleClass = null;
    }

}
