//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.10 at 04:40:43 ip. EEST 
//


package siima.models.jaxb.caex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines base structures for a SystemUnit class definition.
 * 
 * <p>Java class for SystemUnitClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SystemUnitClassType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CAEXObject">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Attribute" type="{}AttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExternalInterface" type="{}InterfaceClassType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InternalElement" type="{}InternalElementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SupportedRoleClass" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXBasicObject">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="MappingObject" type="{}MappingType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="RefRoleClassPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InternalLink" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CAEXObject">
 *                 &lt;attribute name="RefPartnerSideA" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RefPartnerSideB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SystemUnitClassType", propOrder = {
    "attribute",
    "externalInterface",
    "internalElement",
    "supportedRoleClass",
    "internalLink"
})
@XmlSeeAlso({
    InternalElementType.class,
    SystemUnitFamilyType.class
})
public class SystemUnitClassType
    extends CAEXObject
{

    @XmlElement(name = "Attribute")
    protected List<AttributeType> attribute;
    @XmlElement(name = "ExternalInterface")
    protected List<InterfaceClassType> externalInterface;
    @XmlElement(name = "InternalElement")
    protected List<InternalElementType> internalElement;
    @XmlElement(name = "SupportedRoleClass")
    protected List<SystemUnitClassType.SupportedRoleClass> supportedRoleClass;
    @XmlElement(name = "InternalLink")
    protected List<SystemUnitClassType.InternalLink> internalLink;

    /**
     * Gets the value of the attribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeType }
     * 
     * 
     */
    public List<AttributeType> getAttribute() {
        if (attribute == null) {
            attribute = new ArrayList<AttributeType>();
        }
        return this.attribute;
    }

    public boolean isSetAttribute() {
        return ((this.attribute!= null)&&(!this.attribute.isEmpty()));
    }

    public void unsetAttribute() {
        this.attribute = null;
    }

    /**
     * Gets the value of the externalInterface property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalInterface property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalInterface().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InterfaceClassType }
     * 
     * 
     */
    public List<InterfaceClassType> getExternalInterface() {
        if (externalInterface == null) {
            externalInterface = new ArrayList<InterfaceClassType>();
        }
        return this.externalInterface;
    }

    public boolean isSetExternalInterface() {
        return ((this.externalInterface!= null)&&(!this.externalInterface.isEmpty()));
    }

    public void unsetExternalInterface() {
        this.externalInterface = null;
    }

    /**
     * Gets the value of the internalElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internalElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternalElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternalElementType }
     * 
     * 
     */
    public List<InternalElementType> getInternalElement() {
        if (internalElement == null) {
            internalElement = new ArrayList<InternalElementType>();
        }
        return this.internalElement;
    }

    public boolean isSetInternalElement() {
        return ((this.internalElement!= null)&&(!this.internalElement.isEmpty()));
    }

    public void unsetInternalElement() {
        this.internalElement = null;
    }

    /**
     * Gets the value of the supportedRoleClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedRoleClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedRoleClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemUnitClassType.SupportedRoleClass }
     * 
     * 
     */
    public List<SystemUnitClassType.SupportedRoleClass> getSupportedRoleClass() {
        if (supportedRoleClass == null) {
            supportedRoleClass = new ArrayList<SystemUnitClassType.SupportedRoleClass>();
        }
        return this.supportedRoleClass;
    }

    public boolean isSetSupportedRoleClass() {
        return ((this.supportedRoleClass!= null)&&(!this.supportedRoleClass.isEmpty()));
    }

    public void unsetSupportedRoleClass() {
        this.supportedRoleClass = null;
    }

    /**
     * Gets the value of the internalLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internalLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternalLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemUnitClassType.InternalLink }
     * 
     * 
     */
    public List<SystemUnitClassType.InternalLink> getInternalLink() {
        if (internalLink == null) {
            internalLink = new ArrayList<SystemUnitClassType.InternalLink>();
        }
        return this.internalLink;
    }

    public boolean isSetInternalLink() {
        return ((this.internalLink!= null)&&(!this.internalLink.isEmpty()));
    }

    public void unsetInternalLink() {
        this.internalLink = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXObject">
     *       &lt;attribute name="RefPartnerSideA" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RefPartnerSideB" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InternalLink
        extends CAEXObject
    {

        @XmlAttribute(name = "RefPartnerSideA")
        protected String refPartnerSideA;
        @XmlAttribute(name = "RefPartnerSideB")
        protected String refPartnerSideB;

        /**
         * Gets the value of the refPartnerSideA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefPartnerSideA() {
            return refPartnerSideA;
        }

        /**
         * Sets the value of the refPartnerSideA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefPartnerSideA(String value) {
            this.refPartnerSideA = value;
        }

        public boolean isSetRefPartnerSideA() {
            return (this.refPartnerSideA!= null);
        }

        /**
         * Gets the value of the refPartnerSideB property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefPartnerSideB() {
            return refPartnerSideB;
        }

        /**
         * Sets the value of the refPartnerSideB property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefPartnerSideB(String value) {
            this.refPartnerSideB = value;
        }

        public boolean isSetRefPartnerSideB() {
            return (this.refPartnerSideB!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CAEXBasicObject">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="MappingObject" type="{}MappingType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="RefRoleClassPath" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mappingObject"
    })
    public static class SupportedRoleClass
        extends CAEXBasicObject
    {

        @XmlElement(name = "MappingObject")
        protected MappingType mappingObject;
        @XmlAttribute(name = "RefRoleClassPath", required = true)
        protected String refRoleClassPath;

        /**
         * Gets the value of the mappingObject property.
         * 
         * @return
         *     possible object is
         *     {@link MappingType }
         *     
         */
        public MappingType getMappingObject() {
            return mappingObject;
        }

        /**
         * Sets the value of the mappingObject property.
         * 
         * @param value
         *     allowed object is
         *     {@link MappingType }
         *     
         */
        public void setMappingObject(MappingType value) {
            this.mappingObject = value;
        }

        public boolean isSetMappingObject() {
            return (this.mappingObject!= null);
        }

        /**
         * Gets the value of the refRoleClassPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefRoleClassPath() {
            return refRoleClassPath;
        }

        /**
         * Sets the value of the refRoleClassPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefRoleClassPath(String value) {
            this.refRoleClassPath = value;
        }

        public boolean isSetRefRoleClassPath() {
            return (this.refRoleClassPath!= null);
        }

    }

}
