//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.02 at 10:02:46 AM EEST 
//


package siima.models.jaxb.caex;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppInfoEXTRAContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppInfoEXTRAContentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="WriterHeader"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="WriterName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterVendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterVendorURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterRelease" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="LastWritingDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterProjectTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="WriterProjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppInfoEXTRAContentType", propOrder = {
    "writerHeader"
})
public class AppInfoEXTRAContentType {

    @XmlElement(name = "WriterHeader", required = true)
    protected AppInfoEXTRAContentType.WriterHeader writerHeader;

    /**
     * Gets the value of the writerHeader property.
     * 
     * @return
     *     possible object is
     *     {@link AppInfoEXTRAContentType.WriterHeader }
     *     
     */
    public AppInfoEXTRAContentType.WriterHeader getWriterHeader() {
        return writerHeader;
    }

    /**
     * Sets the value of the writerHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppInfoEXTRAContentType.WriterHeader }
     *     
     */
    public void setWriterHeader(AppInfoEXTRAContentType.WriterHeader value) {
        this.writerHeader = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="WriterName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterVendor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterVendorURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterRelease" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="LastWritingDateTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterProjectTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="WriterProjectID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "writerName",
        "writerID",
        "writerVendor",
        "writerVendorURL",
        "writerVersion",
        "writerRelease",
        "lastWritingDateTime",
        "writerProjectTitle",
        "writerProjectID"
    })
    public static class WriterHeader {

        @XmlElement(name = "WriterName")
        protected String writerName;
        @XmlElement(name = "WriterID")
        protected String writerID;
        @XmlElement(name = "WriterVendor")
        protected String writerVendor;
        @XmlElement(name = "WriterVendorURL")
        protected String writerVendorURL;
        @XmlElement(name = "WriterVersion")
        protected String writerVersion;
        @XmlElement(name = "WriterRelease")
        protected String writerRelease;
        @XmlElement(name = "LastWritingDateTime")
        protected String lastWritingDateTime;
        @XmlElement(name = "WriterProjectTitle")
        protected String writerProjectTitle;
        @XmlElement(name = "WriterProjectID")
        protected String writerProjectID;

        /**
         * Gets the value of the writerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterName() {
            return writerName;
        }

        /**
         * Sets the value of the writerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterName(String value) {
            this.writerName = value;
        }

        /**
         * Gets the value of the writerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterID() {
            return writerID;
        }

        /**
         * Sets the value of the writerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterID(String value) {
            this.writerID = value;
        }

        /**
         * Gets the value of the writerVendor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterVendor() {
            return writerVendor;
        }

        /**
         * Sets the value of the writerVendor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterVendor(String value) {
            this.writerVendor = value;
        }

        /**
         * Gets the value of the writerVendorURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterVendorURL() {
            return writerVendorURL;
        }

        /**
         * Sets the value of the writerVendorURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterVendorURL(String value) {
            this.writerVendorURL = value;
        }

        /**
         * Gets the value of the writerVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterVersion() {
            return writerVersion;
        }

        /**
         * Sets the value of the writerVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterVersion(String value) {
            this.writerVersion = value;
        }

        /**
         * Gets the value of the writerRelease property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterRelease() {
            return writerRelease;
        }

        /**
         * Sets the value of the writerRelease property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterRelease(String value) {
            this.writerRelease = value;
        }

        /**
         * Gets the value of the lastWritingDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastWritingDateTime() {
            return lastWritingDateTime;
        }

        /**
         * Sets the value of the lastWritingDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastWritingDateTime(String value) {
            this.lastWritingDateTime = value;
        }

        /**
         * Gets the value of the writerProjectTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterProjectTitle() {
            return writerProjectTitle;
        }

        /**
         * Sets the value of the writerProjectTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterProjectTitle(String value) {
            this.writerProjectTitle = value;
        }

        /**
         * Gets the value of the writerProjectID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWriterProjectID() {
            return writerProjectID;
        }

        /**
         * Sets the value of the writerProjectID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWriterProjectID(String value) {
            this.writerProjectID = value;
        }

    }

}
